/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2015 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2015 Sun Microsystems, Inc.
 */
package com.junichi11.netbeans.modules.github.issues.issue.ui;

import com.junichi11.netbeans.modules.github.issues.GitHubIssuesConfig;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author junichi11
 */
public class ManageTemplatesPanel extends JPanel {

    private static final long serialVersionUID = 7015367673609592404L;
    private final DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form ManageTemplatesPanel
     */
    public ManageTemplatesPanel() {
        initComponents();
        init();
    }

    private void init() {
        resetTemplateNameList();
        templateNameList.setModel(listModel);
        templateNameList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                String selectedValue = templateNameList.getSelectedValue();
                if (selectedValue != null) {
                    // show template
                    setTemplate(selectedValue);
                }
            }
        });
    }

    public void resetTemplateNameList() {
        listModel.clear();
        templateEditorPane.setText(""); // NOI18N
        GitHubIssuesConfig config = GitHubIssuesConfig.getInstance();
        String[] templateNames = config.getTemplateNames();
        for (String templateName : templateNames) {
            listModel.addElement(templateName);
        }
    }

    public String getSelectedTemplateName() {
        return templateNameList.getSelectedValue();
    }

    public void setSelectedTemplateName(String name) {
        templateNameList.setSelectedValue(name, true);
        setTemplate(name);
    }

    private void setTemplate(String templateName) {
        String template = GitHubIssuesConfig.getInstance().getTemplate(templateName);
        templateEditorPane.setText(template);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        templateScrollPane = new javax.swing.JScrollPane();
        templateEditorPane = new javax.swing.JEditorPane();
        templateNameScrollPane = new javax.swing.JScrollPane();
        templateNameList = new javax.swing.JList<String>();

        templateEditorPane.setEditable(false);
        templateScrollPane.setViewportView(templateEditorPane);

        templateNameScrollPane.setViewportView(templateNameList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(templateNameScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(templateScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(templateScrollPane)
                    .addComponent(templateNameScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane templateEditorPane;
    private javax.swing.JList<String> templateNameList;
    private javax.swing.JScrollPane templateNameScrollPane;
    private javax.swing.JScrollPane templateScrollPane;
    // End of variables declaration//GEN-END:variables
}
